branches:
    only:
        - master
git:
    depth: 10

language: cpp

notifications:
    email:
        on_success: never
        on_failure: change

script:
    - "nvm install 12.0 && node --version"
    - "curl -sL https://git.io/fji1w | sh"
